% rosArrayToCell Converts an array of values in a CSV column to a cell
%	rosArrayToCell(input) Converts a string read from a CSV file generated by the bag2csv.py script
%	to a Matlab cell. For instance, converts all of the ranges in a laser scanner message to a cell.
%
%	rosArrayToCell(input, use_parallel) Turn the use of parallel computing features on or off.

%   Copyright (c) 2014 David Anthony
%
%   This program is free software; you can redistribute it and/or modify
%   it under the terms of the GNU General Public License as published by
%   the Free Software Foundation; either version 2 of the License, or
%   (at your option) any later version.
%
%   This program is distributed in the hope that it will be useful,
%   but WITHOUT ANY WARRANTY; without even the implied warranty of
%   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%   GNU General Public License for more details.
%
%   You should have received a copy of the GNU General Public License
%   along with this program; if not, write to the Free Software
%   Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

function [values] = rosArrayToCell(input, use_parallel)

% Sets the optional parallel toolbox features to default to on
if(nargin == 1)
	use_parallel = true;
end

% Pre-allocate output variables
num_samples = size(input, 1);
values = nan(num_samples, numel(strsplit(input{1}, '_')));

% Check for availability of parallel computing features
v = ver;
if(any(strcmp('Parallel Computing Toolbox', {v.Name})) && (use_parallel == true))
	% Go through all the passed in strings, split on the underscores, and convert them to numeric
	% values
	parfor sample_idx = 1:num_samples
		samples = strsplit(input{sample_idx}, '_');
		values(sample_idx, :) = str2double(samples);
	end
else
	% Same idea as the parallel version
	for sample_idx = 1:num_samples
		samples = strsplit(input{sample_idx}, '_');
		values(sample_idx, :) = str2double(samples);
	end
end

% Remove any columns of all invalid entries
values(:, all(isnan(values), 1)) = [];

end