% rosBoolToMatlabLogical Converts an array of true and false strings to an array of logicals
%	rosBoolToMatlabLogical(input) Converts a string array read from a CSV file generated by the 
%	bag2csv.py script to a Matlab array of logicals

%   Copyright (c) 2014 David Anthony
%
%   This program is free software; you can redistribute it and/or modify
%   it under the terms of the GNU General Public License as published by
%   the Free Software Foundation; either version 2 of the License, or
%   (at your option) any later version.
%
%   This program is distributed in the hope that it will be useful,
%   but WITHOUT ANY WARRANTY; without even the implied warranty of
%   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%   GNU General Public License for more details.
%
%   You should have received a copy of the GNU General Public License
%   along with this program; if not, write to the Free Software
%   Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

function [values] = rosBoolToMatlabLogical(input)

values = {strcmp(input, 'True')};
end