% std_msgs_tf_extract Converts a CSV file containing tf data to a Matlab struct
%	std_msgs_tf_extract(filename) filename is the name of the CSV file. Returns the information
%	in the CSV file as a Matlab struct

%   Copyright (c) 2014 David Anthony
%
%   This program is free software; you can redistribute it and/or modify
%   it under the terms of the GNU General Public License as published by
%   the Free Software Foundation; either version 2 of the License, or
%   (at your option) any later version.
%
%   This program is distributed in the hope that it will be useful,
%   but WITHOUT ANY WARRANTY; without even the implied warranty of
%   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%   GNU General Public License for more details.
%
%   You should have received a copy of the GNU General Public License
%   along with this program; if not, write to the Free Software
%   Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

function [bag_data] = std_msgs_tf_extract(filename)
fid = fopen(filename);
% Format of first line with the column names
C = textscan(...
	fid, ...
	'%s%s%n%n%n%n%n%n%n%n%n%n', ...
	'delimiter', ...
	',', ...
	'headerLines', ...
	1);
fclose(fid);

bag_data = struct(...
	'child_frame_id', {C{1}(:)}, ...
	'header_frame_id', {C{2}(:)}, ...
	'seq', C{3}, ...
	'nsecs', C{4}, ...
	'secs', C{5}, ...
	'times', C{5} + (C{4} / 1e9), ...
	'rotation_w', C{6}, ...
	'rotation_x', C{7}, ...
	'rotation_y', C{8}, ...
	'rotation_z', C{9}, ...
	'translation_x', C{10}, ...
	'translation_y', C{11}, ...
	'translation_z', C{12});
end