% std_msgs_tf_extract Converts a CSV file containing tf data to a Matlab struct
%	geometry_msgs_twist_stamped_extract(filename) filename is the name of the CSV file. Returns the 
%	information in the CSV file as a Matlab struct

%   Copyright (c) 2015 David Anthony
%
%   This program is free software; you can redistribute it and/or modify
%   it under the terms of the GNU General Public License as published by
%   the Free Software Foundation; either version 2 of the License, or
%   (at your option) any later version.
%
%   This program is distributed in the hope that it will be useful,
%   but WITHOUT ANY WARRANTY; without even the implied warranty of
%   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%   GNU General Public License for more details.
%
%   You should have received a copy of the GNU General Public License
%   along with this program; if not, write to the Free Software
%   Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

function [bag_data] = geometry_msgs_twist_stamped_extract(filename)
fid = fopen(filename);
% Format of first line with the column names
C = textscan(...
	fid, ...
	'%s%n%n%n%n%n%n%n%n%n', ...
	'delimiter', ...
	',', ...
	'headerLines', ...
	1);
fclose(fid);

bag_data = struct(...
	'header_frame_id', {C{1}(:)}, ...
	'seq', C{2}, ...
	'times', C{4} + (C{3} / 1e9), ...
	'twist_angular_x', C{5}, ...
	'twist_angular_y', C{6}, ...
	'twist_angular_z', C{7}, ...
	'twist_linear_x', C{8}, ...
	'twist_linear_y', C{9}, ...
	'twist_linear_z', C{10});
end